[package]
name = "chaosbf_wasm"
version = "4.0.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
# No external dependencies - fully self-contained

[profile.release]
opt-level = 3
lto = true
strip = false
codegen-units = 1
